apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: |
    ${{ values.description }}
spec:
  owner: ${{ values.owner }}
  lifecycle: production
  type: service